### PR TITLE
Trunk-4830 split pom into modules so that different Liquibase versions can be used

### PR DESCRIPTION
**Pull request by WolfSchlegel**
This pull request splits the pom file into modules that use different Liquibase versions.

@dkayiwa and @gitcliff - this should fix building openmrs-standalone with openmrs-core 2.4.0-SNAPSHOT.

As mentioned before, this version will only work with openmrs-core 2.4.x or higher. 

Any questions, please ask.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Some confli

**Comment by dkayiwa** [comment]
A few conflicting files.

**Comment by WolfSchlegel** [comment]
@dkayiwa the merge conflicts are resolved now

**Comment by dkayiwa** [comment]
@WolfSchlegel is all well now? That is running mvn clean package -Dopenmrs.version=2.4.0-SNAPSHOT

**Comment by WolfSchlegel** [comment]
@dkayiwa yes, please give it a try. I successfully ran the modularised build on my machine.

**Comment by WolfSchlegel** [comment]
Hang on, one variable went missing...

**Comment by WolfSchlegel** [comment]
@dkayiwa one variable for the configuration of an Eclipse plugin had gone missing, it was not needed but I added it nevertheless

Please go ahead and give the new build a try.

**Comment by dkayiwa** [comment]
@WolfSchlegel i consistently get this https://pastebin.com/Hgjw2MJS  on running mvn clean package -Dopenmrs.version=2.4.0-SNAPSHOT

**Comment by WolfSchlegel** [comment]
@dkayiwa checking...

**Comment by WolfSchlegel** [comment]
@dkayiwa could you please run the build with "-X" as additional parameter and share the full log?

`pom-step-01.xml` and `pom-step-02.xml` are using the **same** database url and credentials so I do not understand why the second step fails to connect to the database.

There is one difference between my local test and your tests: I did not use `Connector/MXJ` (as it does not run on my machine) but a local MySQL installation.

It looks like the `mysqld` instance is started and stopped for each module which would explain that the second module cannot connect to the OpenMRS database that was created by the first module.

Hopefully the extended logs can shed some light on this.

**Comment by dkayiwa** [comment]
[daniel.log](https://github.com/openmrs/openmrs-standalone/files/5343593/daniel.log)

**Comment by dkayiwa** [comment]
@WolfSchlegel i have attached the above daniel.log file.

**Comment by WolfSchlegel** [comment]
Thanks @dkayiwa 

In the meantime I started reading the `Connector/MXJ` developer guide: https://downloads.mysql.com/docs/connector-mxj-en.pdf

**Comment by WolfSchlegel** [comment]
@dkayiwa please have look at the logs.

Around line 3418:
```
[/Projects/openmrs/standalone/target/emptydatabase/bin/mysqld][--no-defaults][--basedir=/Projects/openmrs/standalone/target/emptydatabase][--max_allowed_packet=32M][--port=33326][--datadir=/Projects/openmrs/standalone/target/emptydatabase/data][--character-set-server=utf8][--socket=mysql.sock][--collation-server=utf8_general_ci][--pid-file=/Projects/openmrs/standalone/target/emptydatabase/data/MysqldResource.pid]
[MysqldResource] launching mysqld (driver_launched_mysqld_1)
[MysqldResource] mysqld running as process: 88831
```

and around line 37796
```
[INFO] Deleting /Projects/openmrs/standalone/target
```

and finally around line 38296
```
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:2.0.1:update (empty-db-add-ciel-data) on project standalone-02: Error setting up or running Liquibase: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.: Can't create database 'openmrs' (errno: 2) -> [Help 1]
```

The line numbers are approximate as I added a few markers to the log.

When running `mvn clean package -Dopenmrs.version=2.4.0-SNAPSHOT` the `clean` step is executed for each module.

This means that the folder `datadir=/Projects/openmrs/standalone/target/emptydatabase/data` is deleted at the beginning of step 2 and the database created in step 1 is no longer available.

This is an educated guess, please try running the following two commands:
```
mvn clean
mvn package -Dopenmrs.version=2.4.0-SNAPSHOT
```
When running the second command **without** `clean`, the database should be available for the second (and subsequent) steps.

**Comment by WolfSchlegel** [comment]
@dkayiwa I am closing shop for today as I need to start early tomorrow.

Please let me know if running the build in two steps works. If it does not, please share another log.

**Comment by dkayiwa** [comment]
[wolf.log](https://github.com/openmrs/openmrs-standalone/files/5343815/wolf.log)

**Comment by dkayiwa** [comment]
Above is the wolf.log file after running the two commands as you advised.

**Comment by WolfSchlegel** [comment]
@dkayiwa step 3 still contained my local database url, I fixed that.

**Comment by WolfSchlegel** [comment]
Once the build is green, I update the documentation.

**Comment by dkayiwa** [comment]
[another.log](https://github.com/openmrs/openmrs-standalone/files/5346451/another.log)

It has run successfully as per the attached log.
But when i check the target folder, the standalone zip does not exist.

**Comment by dkayiwa** [comment]
Secondly, two mysql processes hang around, after the successful build. Originally, they all got stopped after a successful build. They only stayed around on failed builds.

**Comment by WolfSchlegel** [comment]
@dkayiwa thanks for the update, I check the log and run tests on my side 
in the evening.

**Comment by WolfSchlegel** [comment]
@dkayiwa the zip files are back, a few steps had gone missing in the last step. I took care to double check that all executions that were contained in the original single pom file are available in the new modules.

Regarding the mysqld processes that is hard for me to comment on as `Connector/MXJ` is not working for me. I am running all my tests against a local MySQL database instead.

Please check if you can replicate the hanging processes. The documentation states _"When you have finished with the server, the instance is terminated, and, by default, any data created during the session is retained within the temporary directory created when the instance was started."_ (c.f. https://downloads.mysql.com/docs/connector-mxj-en.pdf).

One thing that could be added to the build steps is to take a short break between the executions of the Liquibase Maven Plugin to ensure that one mysqld process stops properly before starting the next one. But that is a wild guess of mine.

Please try the updated build and let me know the result.

**Comment by dkayiwa** [comment]
[thisone.log](https://github.com/openmrs/openmrs-standalone/files/5351229/thisone.log)

This time the zip was created and the mysql processes all terminated as expected.
Attached is the log, just in case you need it.
Let me now test the zipped standalone.

**Comment by dkayiwa** [comment]
On running to test the packages standalone, i get these errors: https://pastebin.com/EHYVX4Uu
FWIW, i started by getting some other error which i fixed by reverting the tomcat version back to 7.0.50 here: https://github.com/openmrs/openmrs-standalone/blob/master/pom.xml#L16

**Comment by WolfSchlegel** [comment]
Thanks for the log, @dkayiwa 

https://github.com/openmrs/openmrs-standalone/blob/master/Demo-1.9.0.sql needs to be updated. The file adds records for `liquibase-update-to-latest.xml` to the `liquibasechangelog` table but not for Liquibase change sets used for schema creation ad adding core data.

That was sufficient for openmrs-core version 2.3.x and earlier. openmrs-core 2.4.x introduced Liquibase snapshots and during startup the application analyses the change sets that were run before to figure out which Liquibase snapshot had been used when creating the database and which updates need to be applied on top of that.

This check fails for openmrs-standalone as the `liquibasechangelog` table is incomplete.

The solution is to add the missing insert statements to the `Demo-1.9.0.sql` file which I can do over the weekend.

**Comment by dkayiwa** [comment]
Oh i see. Thanks for looking into this! 👍

**Comment by WolfSchlegel** [comment]
@dkayiwa please give this commit a try, it contains the following changes:

- `Demo-1.9.0.sql` now creates additional records in the `liquibasechangelog` table.
- When starting openmrs-standalone, 1.9.x should now be recognised as the snapshots that had been used when creating the database.
- Adding the new insert statement to `Demo-1.9.0.sql` pushed the size of this file over github's 100MB limit so the file was replaced by `Demo-1.9.0.sql.zip`.
- The zip file is unpacked before using it to populate the database.

As before, I tested the changes with my local MySQL database only (as my machine disagrees with `Connector/MXJ`).

**Comment by dkayiwa** [comment]
Now on running to test the packaged standalone, `Demonstration mode` and `Starter Implementation` work correctly.  `Expert Mode` still fails with: https://pastebin.com/QcBnpHxH

**Comment by WolfSchlegel** [comment]
@dkayiwa openmrs-standalone contains two data sets: `demodatabase.zip` and `emptydatabase.zip`. Which data set is used by

- Demonstration mode
- Starter Implementation
- Expert mode

Also, could you please share the logs from starting `Demonstration mode` and `Starter implementation`?

Thank you

**Comment by dkayiwa** [comment]
These are the logs:
`Demonstration mode`: https://pastebin.com/H6r3dbkq
`Starter Implementation`: https://pastebin.com/DT75cVxV
`Expert mode`: https://pastebin.com/wSdVHm28

**Comment by WolfSchlegel** [comment]
@dkayiwa I found the answer to my question by looking at [`org.openmrs.standalone.MainFrame`](https://github.com/openmrs/openmrs-standalone/blob/78020962c58a6e9cc39302290d1d9c4bfb2ace51/src/main/java/org/openmrs/standalone/MainFrame.java).

**Comment by WolfSchlegel** [comment]
@dkayiwa thanks for sharing the logs.

When starting openmrs-standalone in expert mode, the database is deleted. This should result in the initialisation wizard being executed. 

In [`org.openmrs.web.filter.initialization.InitializationFilter`](https://github.com/openmrs/openmrs-core/blob/master/web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java) 

- the database is created at line 1595 
- the initial Liquibase snapshot version is determined at line 1704

Between those lines a few steps are logged, however not at `info` but at `debug` level.

We need to get those logs to understand why the database is not re-created and initialised after it was deleted.

Could you please change the log level of **openmrs-core**? The log level for both `org.openmrs.util.DatabaseUpdater` and `org.openmrs.web.filter.initialization.InitializationFilter` needs to be set to `debug`.

That should give us more insight into what happens when starting **openmrs-standalone** in expert mode.

**Comment by dkayiwa** [comment]
Great to see you back @WolfSchlegel 👍

**Comment by gitcliff** [comment]
sounds awesome and well be back @WolfSchlegel

**Comment by WolfSchlegel** [comment]
@dkayiwa and @gitcliff 

Good news, I simulated the openmrs-standalone `expert` mode by ...

1. initialising OpenMRS
2. dropping the entire database
3. creating an empty database that contains only the `liquibasechangelog` and `liquibasechangeloglock` tables
4. starting OpenMRS based on the `openmrs-runtime.properties` file created in step 1.

It turns out that another check needs to be added to the [org.openmrs.web.Listener#setupNeeded()](https://github.com/openmrs/openmrs-core/blob/aed41971ccb91c82fb88fd52e9eb76348120e64e/web/src/main/java/org/openmrs/web/Listener.java) method. 

The check needed is similar to the one that exists in [org.openmrs.web.filter.initialization.InitializationFilter#isDatabaseEmpty()](https://github.com/openmrs/openmrs-core/blob/master/web/src/main/java/org/openmrs/web/filter/initialization/InitializationFilter.java) around line 1920. 

The purpose of that check is to figure out whether any other tables exist other than `liquibasechangelog` and `liquibasechangeloglock`. If no other table exists `org.openmrs.web.Listener#setupNeeded()` needs to return `true`.

Amending this will take a few days, most likely it should be done by the coming weekend.

**Comment by dkayiwa** [comment]
@WolfSchlegel thank you so much for the investigation and very promising feedback.
Anxiously looking forward to the coming weekend!

**Comment by WolfSchlegel** [comment]
@dkayiwa there are two more pull requests for openmrs-core which should fix the bug in the openmrs-standalone `expert` mode:

- https://github.com/openmrs/openmrs-core/pull/3610 for master
- https://github.com/openmrs/openmrs-core/pull/3611 for 2.4.x

Please test the expert mode based on the PR for 2.4.x.

**Comment by dkayiwa** [comment]
Thank you so much @WolfSchlegel 👍 
I have tested and confirmed that even the expert mode is now fixed!

**Comment by dkayiwa** [comment]
@WolfSchlegel could you be knowing why the standalone build process fails on our bamboo CI? This is the log: https://ci.openmrs.org/download/OP-PLATFORM-BS/build_logs/OP-PLATFORM-BS-29.log

**Comment by WolfSchlegel** [comment]
@dkayiwa that looks familiar, we had experienced that some 18 days ago.

When running `mvn clean package -Dopenmrs.version=2.4.0-SNAPSHOT` the clean step is executed for each module.

This means that the folder `datadir=/<some root dir>/openmrs/standalone/target/emptydatabase/data` is deleted at the beginning of step 2 and the database created in step 1 is no longer available.

The clean step needs to be run separately before the rest of the build:

```
mvn clean
mvn package -Dopenmrs.version=2.4.0-SNAPSHOT
```

When running the second command without clean, the database is available for the second (and subsequent) steps.

**Comment by dkayiwa** [comment]
Shame on me for having forgotten what you told me to do above. 😊 
It works after doing exactly so. Thanks @WolfSchlegel 👍

**Comment by WolfSchlegel** [comment]
No worries @dkayiwa , I actually had to remind myself of what we found earlier... 

It is good that we got it working, thank you for all the testing on your side.

**Pull request merged**
